-- 코드를 입력하세요
SELECT T.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR, (SELECT BOOK.AUTHOR_ID, CATEGORY, SUM(SALES) * PRICE AS TOTAL_SALES
FROM BOOK_SALES LEFT JOIN BOOK
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK_SALES.BOOK_ID) T
WHERE T.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC