SELECT CART_ID 
FROM (SELECT CART_ID, GROUP_CONCAT(NAME) AS NAME
FROM  CART_PRODUCTS
WHERE NAME LIKE 'Milk' OR NAME LIKE 'Yogurt'
GROUP BY CART_ID) T
WHERE NAME LIKE '%Yogurt%' AND NAME LIKE '%Milk%' 
ORDER BY CART_ID
