WITH SECOND AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID
                        FROM ECOLI_DATA
                        WHERE PARENT_ID IS NULL)
)
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID
                    FROM SECOND)
ORDER BY ID