-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT AS P LEFT JOIN OFFLINE_SALE AS O
ON P.PRODUCT_ID	 = O.PRODUCT_ID
WHERE SALES_AMOUNT IS NOT NULL
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE 