-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, ROUND((DAILY_FEE * 30 * 0.01 * (100 - 
(SELECT DISCOUNT_RATE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE DURATION_TYPE  = '30일 이상' AND CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE = CAR_RENTAL_COMPANY_CAR.CAR_TYPE))))
AS FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN
    (SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        OR (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30'))
    AND (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') 
    AND ROUND((DAILY_FEE * 30 * 0.01 * (100 - 
            (SELECT DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
            WHERE DURATION_TYPE  = '30일 이상' AND CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE = CAR_RENTAL_COMPANY_CAR.CAR_TYPE)))) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC