SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS LEFT JOIN ANIMAL_OUTS USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male')
ORDER BY ANIMAL_INS.ANIMAL_ID