SELECT FISH_COUNT, FISH_NAME
FROM FISH_NAME_INFO
RIGHT JOIN (SELECT COUNT(ID) AS FISH_COUNT, FISH_TYPE
            FROM FISH_INFO
            GROUP BY FISH_TYPE) C
ON FISH_NAME_INFO.FISH_TYPE = C.FISH_TYPE
ORDER BY FISH_COUNT DESC