-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR , MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS
, Round(COUNT(DISTINCT S.USER_ID) / 
(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS S LEFT JOIN USER_INFO AS U
ON S.USER_ID = U.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH