WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, 1+ P.GENERATION
    FROM ECOLI_DATA E
    INNER JOIN GEN P ON E.PARENT_ID = P.ID
), PARENTS AS (
    SELECT DISTINCT(PARENT_ID) AS ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
LEFT JOIN PARENTS ON GEN.ID = PARENTS.ID
WHERE PARENTS.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION
