WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, GENERATION+1
    FROM GEN, ECOLI_DATA
    WHERE ECOLI_DATA.PARENT_ID = GEN.ID
), PARENTS AS (
    SELECT DISTINCT(PARENT_ID) AS PARENT_ID
    FROM ECOLI_DATA
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM GEN
LEFT JOIN PARENTS ON GEN.ID = PARENTS.PARENT_ID
WHERE PARENTS.PARENT_ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION
