-- 코드를 입력하세요
SELECT HISTORY_ID,
ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 0.01 * (100 -
IFNULL((SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE "트럭" 
AND (DURATION_TYPE LIKE CASE
WHEN (DATEDIFF(END_DATE, START_DATE) + 1) BETWEEN 7 AND 29 THEN '7일 이상'
WHEN (DATEDIFF(END_DATE, START_DATE) + 1) BETWEEN 30 AND 90 THEN '30일 이상'
WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
ELSE NULL END)),0)))
AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE LIKE "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC 