-- 코드를 입력하세요
SELECT APNT_NO,	PT_NAME, APPOINTMENT.PT_NO, 
APPOINTMENT.MCDP_CD, DR_NAME, 
APNT_YMD
FROM DOCTOR, APPOINTMENT LEFT JOIN PATIENT
ON APPOINTMENT.PT_NO = PATIENT.PT_NO
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') LIKE '2022-04-13'
AND MDDR_ID = DR_ID AND APNT_CNCL_YN LIKE 'N'
ORDER BY APNT_YMD