SELECT ITEM_INFO.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
RIGHT JOIN (SELECT ITEM_ID	
            FROM ITEM_TREE
            WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID	
                                     FROM ITEM_INFO
                                     WHERE RARITY LIKE 'RARE')) ID
ON ITEM_INFO.ITEM_ID = ID.ITEM_ID
ORDER BY ITEM_ID DESC
