SELECT ECOLI_DATA.ID, GENOTYPE, PARENT_GENOTYPE
FROM ECOLI_DATA
LEFT JOIN (SELECT ID, GENOTYPE AS PARENT_GENOTYPE
           FROM ECOLI_DATA) AS P
ON ECOLI_DATA.PARENT_ID = P.ID
WHERE NOT PARENT_GENOTYPE IS NULL AND GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY ECOLI_DATA.ID
