-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
WHERE START_DATE BETWEEN '2022-10-01' AND '2022-10-31'AND CAR_TYPE = '세단'
ORDER BY H.CAR_ID DESC