SELECT SCORE, HR_EMPLOYEES.EMP_NO,  EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES RIGHT JOIN 
(SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY SCORE DESC LIMIT 1) SCORE
ON SCORE.EMP_NO =  HR_EMPLOYEES.EMP_NO