-- 코드를 입력하세요
SELECT M.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) M LEFT JOIN FOOD_PRODUCT
ON M.CATEGORY = FOOD_PRODUCT.CATEGORY AND M.MAX_PRICE = FOOD_PRODUCT.PRICE
ORDER BY MAX_PRICE DESC